Make tox -e coverage work
nose-based version was failing for me:

$ tox -e coverage
coverage recreate: /home/mg/src/zopefoundation/zdaemon/.tox/coverage
coverage installdeps: zc.customdoctests, zope.testing, zope.testrunner, manuel, mock, nose, coverage, nosexcover
coverage develop-inst: /home/mg/src/zopefoundation/zdaemon
coverage runtests: PYTHONHASHSEED='555400718'
coverage runtests: commands[0] | nosetests --with-xunit --with-xcoverage
E....E.........................E..............EEEE.EEEEEE.EE..............
======================================================================
ERROR: test suite for <module 'zdaemon.tests.tests' from '/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/tests.pyc'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/.tox/coverage/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/mg/src/zopefoundation/zdaemon/.tox/coverage/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/mg/src/zopefoundation/zdaemon/.tox/coverage/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/mg/src/zopefoundation/zdaemon/.tox/coverage/local/lib/python2.7/site-packages/nose/util.py", line 469, in try_run
    return func(obj)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/tests.py", line 321, in setUp
    test.globs['_td'] = td = []
AttributeError: 'module' object has no attribute 'globs'

======================================================================
ERROR: help_test_helper (zdaemon.tests.testzdoptions.TestBasicFunctionality)
----------------------------------------------------------------------
TypeError: help_test_helper() takes exactly 4 arguments (1 given)

======================================================================
ERROR: help_test_helper (zdaemon.tests.testzdoptions.TestZDOptions)
----------------------------------------------------------------------
TypeError: help_test_helper() takes exactly 4 arguments (1 given)

======================================================================
ERROR: testCtlRunDirectoryCreation (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 328, in testCtlRunDirectoryCreation
    self.run_ctl(['-z', path, '-p', self.cmd])
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 323, in run_ctl
    proc = zdctl.ZDCmd(options)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 147, in __init__
    self.create_rundir()
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 154, in create_rundir
    self.create_directory(self.options.directory)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 169, in create_directory
    os.chown(directory, self.options.uid, self.options.gid)
TypeError: an integer is required

======================================================================
ERROR: testCtlRunDirectoryCreation (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 316, in tearDown
    self.assertEqual(self.expect, got)
AssertionError: '/bin/true\n' != ''

======================================================================
ERROR: testCtlRunDirectoryCreationFromConfigFile (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 337, in testCtlRunDirectoryCreationFromConfigFile
    self.run_ctl(['-C', config])
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 323, in run_ctl
    proc = zdctl.ZDCmd(options)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 147, in __init__
    self.create_rundir()
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 154, in create_rundir
    self.create_directory(self.options.directory)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 169, in create_directory
    os.chown(directory, self.options.uid, self.options.gid)
TypeError: an integer is required

======================================================================
ERROR: testCtlRunDirectoryCreationFromConfigFile (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 316, in tearDown
    self.assertEqual(self.expect, got)
AssertionError: '/bin/true\n' != ''

======================================================================
ERROR: testCtlSocketDirectoryCreation (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 351, in testCtlSocketDirectoryCreation
    self.run_ctl(['-s', path, '-p', self.cmd])
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 323, in run_ctl
    proc = zdctl.ZDCmd(options)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 148, in __init__
    self.create_socket_dir()
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 160, in create_socket_dir
    self.create_directory(dir)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 169, in create_directory
    os.chown(directory, self.options.uid, self.options.gid)
TypeError: an integer is required

======================================================================
ERROR: testCtlSocketDirectoryCreation (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 316, in tearDown
    self.assertEqual(self.expect, got)
AssertionError: '/bin/true\n' != ''

======================================================================
ERROR: testCtlSocketDirectoryCreationFromConfigFile (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 375, in testCtlSocketDirectoryCreationFromConfigFile
    self.run_ctl(['-C', config])
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 323, in run_ctl
    proc = zdctl.ZDCmd(options)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 148, in __init__
    self.create_socket_dir()
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 160, in create_socket_dir
    self.create_directory(dir)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 169, in create_directory
    os.chown(directory, self.options.uid, self.options.gid)
TypeError: an integer is required

======================================================================
ERROR: testCtlSocketDirectoryCreationFromConfigFile (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 316, in tearDown
    self.assertEqual(self.expect, got)
AssertionError: '/bin/true\n' != ''

======================================================================
ERROR: testCtlSocketDirectoryCreationFromConfigFileRelativePath (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 384, in testCtlSocketDirectoryCreationFromConfigFileRelativePath
    self.run_ctl(['-C', config])
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 323, in run_ctl
    proc = zdctl.ZDCmd(options)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 148, in __init__
    self.create_socket_dir()
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 160, in create_socket_dir
    self.create_directory(dir)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 169, in create_directory
    os.chown(directory, self.options.uid, self.options.gid)
TypeError: an integer is required

======================================================================
ERROR: testCtlSocketDirectoryCreationFromConfigFileRelativePath (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 316, in tearDown
    self.assertEqual(self.expect, got)
AssertionError: '/bin/true\n' != ''

======================================================================
ERROR: testCtlSocketDirectoryCreationRelativePath (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 356, in testCtlSocketDirectoryCreationRelativePath
    self.run_ctl(['-s', path, '-p', self.cmd])
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 323, in run_ctl
    proc = zdctl.ZDCmd(options)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 148, in __init__
    self.create_socket_dir()
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 160, in create_socket_dir
    self.create_directory(dir)
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/zdctl.py", line 169, in create_directory
    os.chown(directory, self.options.uid, self.options.gid)
TypeError: an integer is required

======================================================================
ERROR: testCtlSocketDirectoryCreationRelativePath (zdaemon.tests.testzdrun.TestRunnerDirectory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mg/src/zopefoundation/zdaemon/src/zdaemon/tests/testzdrun.py", line 316, in tearDown
    self.assertEqual(self.expect, got)
AssertionError: '/bin/true\n' != ''